import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Script from "next/script";
import "./globals.css";
// import "bootstrap/dist/css/bootstrap.css";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget }  from "@/components/PopupWidget";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    //<html className="bg-[lightblue]" lang="en" suppressHydrationWarning>
    //<html className="bg-gradient-to-l from-blue-400 to-violet-300 dark:from-blue-400 dark:to-violet-400" lang="en" suppressHydrationWarning>
//<html className="bg-gradient-to-l from-blue-400 to-violet-300 dark:from-blue-400 dark:to-violet-400" lang="en" suppressHydrationWarning>
      <html className="bg-gradient-to-r from-violet-300 to-cyan-500" lang="en" suppressHydrationWarning>
    
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <Navbar/>
          <div>{children}</div>
          <Footer />
          <PopupWidget />
        </ThemeProvider>
        <script src="./node_modules/preline/dist/preline.js" async></script>
        <script src="" async></script>
      </body>
    </html>
  );
}
